
name: dolos
version: "3.9"
services:
  db:
    image: mariadb:11
    volumes:
      - dolos-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dolos
    healthcheck:
      start_period: 2s
      interval: 5s
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
  web:
    image: ghcr.io/dodona-edu/dolos-web
    build: ./web/
    environment:
      VITE_HOST: 0.0.0.0
      VITE_PORT: 8080
      VITE_API_URL: https://dolos.cs.aalto.fi/api
      VITE_MODE: server
    depends_on:
      - api
    networks:
      - dolos
    healthcheck:
      start_period: 2s
      interval: 5s
      test: curl --fail http://localhost:8080 || exit 1
  api:
    image: ghcr.io/dodona-edu/dolos-api
    build: ./api/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - dolos-api-storage:/dolos/storage
      - /tmp:/tmp
    environment:
      DOLOS_API_FRONT_END_URL: https://dolos.cs.aalto.fi
      DOLOS_API_URL: https://dolos.cs.aalto.fi/api
      DOLOS_API_DISABLE_FORCE_SSL: false
      DOLOS_API_DATABASE_USERNAME: root
      DOLOS_API_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DOLOS_API_DATABASE_HOST: db
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE_DUMMY: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dolos
        #    healthcheck:
        #      start_period: 2s
        #      interval: 10s
        #      test: curl --fail http://localhost:3000/up || exit 1
  worker:
    image: ghcr.io/dodona-edu/dolos-api
    build: ./api/
    command: bash -c "bundle exec rails jobs:work"
    volumes:
      - dolos-api-storage:/dolos/storage
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOLOS_API_FRONT_END_URL: https://dolos.cs.aalto.fi
      DOLOS_API_HOSTS: dolos.cs.aalto.fi
      DOLOS_API_DATABASE_USERNAME: root
      DOLOS_API_DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DOLOS_API_DATABASE_HOST: db
      RAILS_ENV: production
      SECRET_KEY_BASE_DUMMY: true
      RAILS_LOG_TO_STDOUT: true
    depends_on:
      - api
    networks:
      - dolos
    healthcheck:
      start_period: 2s
      interval: 5s
      test: ruby -e true || exit 1
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/ssl/private/fullchain.pem
      - ./privkey.pem:/etc/ssl/private/privkey.pem
    ports:
      - "443:443"
      - "80:80"
    restart: always
    networks:
      - dolos
    depends_on:
      - api
      - web

volumes:
  dolos-db-data:
  dolos-api-storage:

networks:
  dolos:
